"""Command line interface for the public demo."""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path

from .agent_interface import write_agent_interface
from .analysis_agent import build_analysis_context
from .classifier import FileClassifier
from .dashboard import export_dashboard
from .field_mapper import FieldMapper
from .ingest import ingest_paths, summarize
from .metrics import DEFAULT_METRIC_SPECS, load_metric_specs
from .validation import ValidationResult, validate_profile


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the spreadsheet operations demo pipeline.")
    subcommands = parser.add_subparsers(dest="command", required=True)

    run = subcommands.add_parser("run", help="Ingest files and export dashboard.")
    run.add_argument("--input", required=True, type=Path, help="Input folder with CSV/XLSX files.")
    run.add_argument("--output", required=True, type=Path, help="Output folder.")
    run.add_argument("--file-types", type=Path, default=Path("config/sample_file_types.json"))
    run.add_argument("--field-mapping", type=Path, default=Path("config/sample_field_mapping.json"))
    run.add_argument("--metrics", type=Path, default=Path("config/sample_metrics.json"))
    run.add_argument("--min-confidence", type=float, default=0.2, help="Minimum file classification confidence.")
    run.add_argument("--max-file-mb", type=float, default=25.0, help="Skip input files larger than this size. Use 0 to disable.")
    run.add_argument("--skip-config-validation", action="store_true", help="Run without validating config files first.")

    spec = subcommands.add_parser("agent-spec", help="Export machine-readable integration contract.")
    spec.add_argument("--output", required=True, type=Path, help="JSON output path.")

    analysis = subcommands.add_parser("analysis-context", help="Build structured context for an analysis agent.")
    analysis.add_argument("--summary", required=True, type=Path, help="summary.json generated by the run command.")
    analysis.add_argument("--output", required=True, type=Path, help="JSON output path.")

    validate = subcommands.add_parser("validate-config", help="Validate source, field, and metric config files.")
    validate.add_argument("--file-types", type=Path, default=Path("config/sample_file_types.json"))
    validate.add_argument("--field-mapping", type=Path, default=Path("config/sample_field_mapping.json"))
    validate.add_argument("--metrics", type=Path, default=Path("config/sample_metrics.json"))

    args = parser.parse_args()
    if args.command == "run":
        return _run(args)
    if args.command == "agent-spec":
        write_agent_interface(args.output)
        print(f"Agent interface: {args.output}")
        return 0
    if args.command == "analysis-context":
        build_analysis_context(args.summary, args.output)
        print(f"Analysis context: {args.output}")
        return 0
    if args.command == "validate-config":
        return _validate_config(args)
    return 2


def _run(args: argparse.Namespace) -> int:
    input_dir: Path = args.input
    output_dir: Path = args.output
    if not input_dir.exists() or not input_dir.is_dir():
        print(f"Input folder not found: {input_dir}")
        return 2

    if not args.skip_config_validation:
        validation = validate_profile(args.file_types, args.field_mapping, args.metrics)
        _print_validation(validation)
        if not validation.ok:
            return 2

    discovered_paths = sorted(
        path for path in input_dir.iterdir()
        if path.suffix.lower() in {".csv", ".xlsx", ".xlsm"}
    )
    paths, size_warnings = _filter_by_size(discovered_paths, max_file_mb=args.max_file_mb)
    if not discovered_paths:
        size_warnings.append("No supported input files found.")
    elif not paths:
        size_warnings.append("All supported input files were skipped.")
    try:
        classifier = FileClassifier.from_json(args.file_types) if args.file_types.exists() else FileClassifier()
        mapper = FieldMapper.from_json(args.field_mapping) if args.field_mapping.exists() else FieldMapper()
        metric_specs = load_metric_specs(args.metrics) if args.metrics.exists() else DEFAULT_METRIC_SPECS
        records, ingest_warnings = ingest_paths(paths, classifier, mapper, min_confidence=args.min_confidence)
        warnings = size_warnings + ingest_warnings
        summary = summarize(records, file_count=len(paths), warnings=warnings, metric_specs=metric_specs)
    except (OSError, ValueError) as exc:
        print(f"Run error: {exc}")
        return 2

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "summary.json").write_text(json.dumps(asdict(summary), ensure_ascii=False, indent=2), encoding="utf-8")
    export_dashboard(summary, output_dir / "dashboard.html")

    print(f"Files: {len(paths)}")
    print(f"Records: {len(records)}")
    print(f"Dashboard: {output_dir / 'dashboard.html'}")
    for warning in warnings:
        print(f"Data warning: {warning}")
    return 0


def _validate_config(args: argparse.Namespace) -> int:
    validation = validate_profile(args.file_types, args.field_mapping, args.metrics)
    _print_validation(validation)
    if validation.ok:
        print("Config validation: OK")
        return 0
    return 2


def _filter_by_size(paths: list[Path], max_file_mb: float) -> tuple[list[Path], list[str]]:
    if max_file_mb <= 0:
        return paths, []

    max_bytes = int(max_file_mb * 1024 * 1024)
    included: list[Path] = []
    warnings: list[str] = []
    for path in paths:
        try:
            size = path.stat().st_size
        except OSError as exc:
            warnings.append(f"{path.name}: cannot stat file size ({exc})")
            continue
        if size > max_bytes:
            warnings.append(f"{path.name}: skipped because file size exceeds {max_file_mb:g} MB")
            continue
        included.append(path)
    return included, warnings


def _print_validation(validation: ValidationResult) -> None:
    for warning in validation.warnings:
        print(f"Config warning: {warning}")
    for error in validation.errors:
        print(f"Config error: {error}")


if __name__ == "__main__":
    raise SystemExit(main())
